branch-defaults:
  default:
    environment: image-filter-starter-code-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-starter-code
  branch: null
  default_ec2_keyname: MIIEogIBAAKCAQEAri3ehdCeR8OcHKnOQmuzy2cvUfEP4S4M4xvRF1bxQV6x3pJ9hoQVcFfbZ8y2
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
